# fly.toml app configuration file generated for torchby on 2023-08-24T20:05:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "torchby"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5056
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
